apiVersion: v1
kind: Pod
metadata:
  name: colab-gpu-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: nvidia.com/gpu.product
              operator: NotIn
              values:
                - NVIDIA-GeForce-GTX-1080-Ti
                - NVIDIA-GeForce-GTX-1080

  containers:
  - name: gpu-container
    image: us-docker.pkg.dev/colab-images/public/runtime
    command: ["sleep", "infinity"]
    resources:
      requests:
        cpu: "1"
        memory: "16Gi"
        ephemeral-storage: "30Gi"
      limits:
        cpu: "8"
        memory: "32Gi"
        ephemeral-storage: "50Gi"
        nvidia.com/gpu: 1
    env:
      - name: "SUBDIR"
        value: "prey_capture"
      - name: "VIDEODIR"
        value: "s3://hengenlab/yolo_videos/"
      - name: "ENDPOINT"
        value: "https://s3-central.nrp-nautilus.io"
      - name: "MODELNAME"
        value: "best.pt"
      - name: "SUBDIR_LOWERCASE"
        value: "${SUBDIR_LOWERCASE}"
      - name: "MAX_JOBS"
        value: "4"
    volumeMounts:
      - name: "prp-s3-credentials"
        mountPath: "/root/.aws/credentials"
        subPath: "credentials"
      - name: "dshm"
        mountPath: "/dev/shm"

  tolerations:
    - key: "nautilus.io/chase-ci"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

  volumes:
    - name: prp-s3-credentials
      secret:
        secretName: prp-s3-credentials
    - name: dshm
      emptyDir:
        medium: Memory    
