apiVersion: batch/v1
kind: Job
metadata:
  name: tovitu-yolo-predict-${TAG}
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never  # Never | OnFailure

      containers:
      - name: tovitu-container
        image: tovitu/hlmice-yolo:latest
        imagePullPolicy: Always

        resources:
          requests:
            cpu: "2"
            memory: "8Gi"
            ephemeral-storage: "20Gi"
          limits:
            cpu: "4"
            memory: "16Gi"
            ephemeral-storage: "50Gi"
            nvidia.com/gpu: 1

        command: ["stdbuf", "-oL", "-eL", "/bin/bash", "-c"]
        args:
          - >-
            bash scripts/detect_roach_parallel.sh;
            
        env:
          - name: "SUBDIR"
            value: "prey_capture"
          - name: "MAX_JOBS"
            value: "4"
          - name: "ANIMAL"
            value: "${ANIMAL}"
          - name: "VIDEODIR"
            value: "s3://hengenlab/yolo_videos/"
          - name: "ENDPOINT"
            value: "https://s3-central.nrp-nautilus.io"
          - name: "MODELNAME"
            value: "best_neg.pt"

        volumeMounts:
          - name: "prp-s3-credentials"
            mountPath: "/root/.aws/credentials"
            subPath: "credentials"

      tolerations:
        - key: "nautilus.io/chase-ci"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
          
      volumes:
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
    
